name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master # or 'main' if that's your default branch
  workflow_dispatch: # allows manual manual deploy from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Recommended for Next.js 14+

      # ✅ Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # ✅ Step 4: Use Firebase-specific Next.js config
      - name: Use Firebase static Next.js config
        run:
          cp next.config.firebase.ts next.config.ts

          # ✅ Step 5: Debug env vars (remove after first success)
      - name: Debug env variables
        run: |
          echo "Checking Firebase environment variables..."
          echo "PROJECT_ID: $NEXT_PUBLIC_FIREBASE_PROJECT_ID"
          echo "API_KEY length: ${#NEXT_PUBLIC_FIREBASE_API_KEY}"
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}

      # ✅ Step 6: Build the Next.js project
      - name: Build Next.js project
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: npm run build

      # ✅ Step 6: Deploy to Firebase Hosting / App Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}" # for GitHub integration
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITA_NEWSEEKERAPP_2020 }}" # service account JSON
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }} # your CI token
